"""add profile_picture to user

Revision ID: 6b5da100e6a5
Revises: 81d98d360129
Create Date: 2025-07-28 12:36:32.698433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6b5da100e6a5'
down_revision: Union[str, None] = '81d98d360129'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversations', 'language',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('EN', 'ES', 'PT', name='language'),
               existing_nullable=False)
    op.alter_column('conversations', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('conversations', 'ended_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('ix_conversations_id'), 'conversations', ['id'], unique=False)
    op.drop_constraint('conversations_user_id_fkey', 'conversations', type_='foreignkey')
    op.create_foreign_key(None, 'conversations', 'users', ['user_id'], ['id'])
    op.alter_column('messages', 'sender',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('USER', 'BOT', name='messagesender'),
               existing_nullable=False,
               postgresql_using="sender::messagesender")
    op.alter_column('messages', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.drop_constraint('messages_conversation_id_fkey', 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'conversations', ['conversation_id'], ['id'])
    op.add_column('users', sa.Column('profile_picture', sa.String(), nullable=True))
    op.alter_column('users', 'contact_method',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('EMAIL', 'WHATSAPP', 'PHONE', 'INSTAGRAM', 'FACEBOOK', 'LINKEDIN', 'TELEGRAM', name='contactmethod'),
               existing_nullable=False,
               postgresql_using="contact_method::contactmethod")
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'contact_method',
               existing_type=sa.Enum('EMAIL', 'WHATSAPP', 'PHONE', 'INSTAGRAM', 'FACEBOOK', 'LINKEDIN', 'TELEGRAM', name='contactmethod'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('users', 'profile_picture')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key('messages_conversation_id_fkey', 'messages', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.alter_column('messages', 'timestamp',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('messages', 'sender',
               existing_type=sa.Enum('USER', 'BOT', name='messagesender'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.create_foreign_key('conversations_user_id_fkey', 'conversations', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_conversations_id'), table_name='conversations')
    op.alter_column('conversations', 'ended_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('conversations', 'started_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
op.alter_column('conversations', 'language',
           existing_type=sa.VARCHAR(length=10),
           type_=sa.Enum('EN', 'ES', 'PT', name='language'),
           existing_nullable=False,
           postgresql_using="language::language")
    # ### end Alembic commands ###
